Repository Ayush7614/Soomvaar, pull requests merged in 2021-10, with the labels that each got.

#166 Predicting the chances of Costumer buying through ADs
  predicting_costumer_buying_chances_through_ads-main/Dataset/Social_Network_Ads.csv
  predicting_costumer_buying_chances_through_ads-main/Predicting_through_logistic_regression.ipynb
  predicting_costumer_buying_chances_through_ads-main/README.md
Labels: open source, hacktoberfest21, hacktober-accepted

#170 Food Recommendation System
  Food_Recommendation_system_basic-main/Datasets/Market_Basket_Optimisation.csv
  Food_Recommendation_system_basic-main/README.md
  Food_Recommendation_system_basic-main/apriori.ipynb
Labels: open source, hacktoberfest21, hacktoberfest-accepted

#172 Amazon Stock price Prediction
  Amazon_Stock_Market_Prediction_using_lstm-main/Amazon_LSTM.ipynb
  Amazon_Stock_Market_Prediction_using_lstm-main/Datasets/Amazon_Stock_Price_Test.csv
  Amazon_Stock_Market_Prediction_using_lstm-main/Datasets/Amazon_Stock_Price_Train.csv
  Amazon_Stock_Market_Prediction_using_lstm-main/README.md
Labels: open source, hacktoberfest21, hacktoberfest-accepted

#174 Bag of Words NLP
  Bag of Models (NLP)/Datasets/Restaurant_Reviews.tsv
  Bag of Models (NLP)/README.md
  Bag of Models (NLP)/natural_language_processing.ipynb
Labels: open source, hacktoberfest21, hacktoberfest-accepted

#176 Added Emotion Recognition using ML
  Facial Expression Recognition Using ML/Model/Emotion_Recognition_ML.ipynb
  Facial Expression Recognition Using ML/Model/requirements.txt
  Facial Expression Recognition Using ML/README.md
  Facial Expression Recognition Using ML/images/10.png
  Facial Expression Recognition Using ML/images/8.png
  Facial Expression Recognition Using ML/images/9.png
  Facial Expression Recognition Using ML/images/result.png
Labels: open source, hacktoberfest21, hacktoberfest-accepted

#179 Add Dogecoin Price Prediction
  Dogecoin Price Prediction/Dataset/coin_Dogecoin.csv
  Dogecoin Price Prediction/Model/dogecoin_price_predition.ipynb
  Dogecoin Price Prediction/README.md
Labels: accepted, open source, hacktoberfest21, hacktoberfest-accepted

#185 Create auto_assign.yml
  .github/auto_assign.yml
Labels: open source, hacktoberfest2021, hacktoberfest-accepted

#181 Added Commercial Sales Prediction Analysis using Regression
  Commercial Sales Prediction Analysis using Regression/Commercial Sales Prediction Analysis using Regression.ipynb
  Commercial Sales Prediction Analysis using Regression/README.md
Labels: open source, hacktoberfest2021, hacktoberfest-accepted

#193 Heart Failure Prediction Project Using AdaBoost and XGBoost
  Heart Failure Prediction Project Using XGBoost/Heart Failure Prediction Project.ipynb
  Heart Failure Prediction Project Using XGBoost/README.md
Labels: open source, hacktoberfest2021, hacktoberfest-accepted

#192 Percentage Prediction of a student
  Percentage Prediction of a student/Dataset.csv
  Percentage Prediction of a student/Percentage Prediction of a student.ipynb
  Percentage Prediction of a student/README.md
Labels: hacktoberfest2021, hacktoberfest-accepted

#199 Optimum number of clusters prediction
  Optimum number of clusters prediction/Iris Dataset.csv
  Optimum number of clusters prediction/Optimum number of clusters prediction using Iris Dataset.ipynb
  Optimum number of clusters prediction/README.md
Labels: open source, hacktoberfest2021, hacktoberfest-accepted
